# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_for_testing2 do
    xcodebuild(
        scheme: "Stopwatch",
        workspace: "Stopwatch.xcworkspace",
        destination: "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2.2",
        xcargs: "build-for-testing -derivedDataPath 'build'"
      )
  end

  lane :uitest do
       xcodebuild(
        scheme: "Stopwatch",
        workspace: "Stopwatch.xcworkspace",
        xcpretty: true,
        xcargs: "-only-testing:StopwatchUITests/StopwatchUITests/testReset -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.2.2' test-without-building -derivedDataPath 'build'"
      )
   end
end
